/// Generated by Flutter GetX Starter on 2022-03-25 13:23
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_base/app/app.dart';
import 'package:flutter_base/app/services/auth_service.dart';

import 'app/di/dependency_creator.dart';
import 'app/utils/dev_http_overrides.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  HttpOverrides.global = DevHttpOverrides();
  await initServices();
  await DependencyCreator().init();
  runApp(const App());
}

initServices() async {
  await AuthService().init();
}
